### ISSUE TITLE
Task not stored. State lost on reload.

### ISSUE THREAD

**Issue by OutdatedGuy** [malivinayak/To-Do-Manager#1]
## Issue
After refreshing the browser the tasks added are lost.

## Solution
Using browser local storage to save tasks and read them when refreshed

**Comment by malivinayak** [comment]
Thank You for reporting
I will definitely work on it

**Comment by OutdatedGuy** [comment]
@malivinayak any updates?

**Comment by malivinayak** [comment]
Not yet
Currently busy in other stuff

**Comment by malivinayak** [comment]
@OutdatedGuy Closing issue as complete at #18
