### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Mouli-3542** [malivinayak/To-Do-Manager#26]
Can I contribute by making some changes ..will u label it as Hactoberfest.

**Comment by malivinayak** [comment]
Yes.

**Comment by Mouli-3542** [comment]
@malivinayak 😀❤️

**Comment by malivinayak** [comment]
> Can I contribute by making some changes ..will u label it as Hactoberfest.

You can easily contribute in this repo https://github.com/malivinayak/Markdown
