### ISSUE TITLE
Css Changes and Text Correction

### ISSUE THREAD

**Issue by Mouli-3542** [malivinayak/To-Do-Manager#27]
As we can see the text named **Task lists** is not visible due to the similar background. Also the text in the place holder was wrong **What would you link to add**...it should be **What would you like to add**.
![before](https://github.com/malivinayak/To-Do-Manager/assets/143725284/9e6b1f7b-fbad-4af4-b655-383fba953007)
I have made some minor changes in the text's **Colour** also corrected the **Placeholder's** text...If u liked it i can make a pull request❤️
![after](https://github.com/malivinayak/To-Do-Manager/assets/143725284/234c1820-bc38-44e3-bffa-4ad9dd1a043b)

**Comment by malivinayak** [comment]
LGTM

**Comment by Mouli-3542** [comment]
Can u assign this to me??

**Comment by malivinayak** [comment]
PR must be named as `style: Title and input placeholder`

and in description mention `Resolves #27`
