### ISSUE TITLE
Adding Dark theme

### ISSUE THREAD

**Issue by Mouli-3542** [malivinayak/To-Do-Manager#32]
**Dark Theme**
![darkmode](https://github.com/malivinayak/To-Do-Manager/assets/143725284/9d29d2b0-0273-4d62-bd03-4d8c8cddcb72)
**Light Theme**
![lightmode](https://github.com/malivinayak/To-Do-Manager/assets/143725284/ff60f955-297f-4144-9999-674ed388f86f)
Will make a **_PR_** if u liked it!

**Comment by Mouli-3542** [comment]
nvm ....working on another this one is not good

**Comment by malivinayak** [comment]
> nvm ....working on another this one is not good

Just make sure your branch is updated with latest changes as more peoples are contributing.
