### ISSUE TITLE
Bug in adding task

### ISSUE THREAD

**Issue by GbCderr14** [malivinayak/To-Do-Manager#33]
User is able to add same todo task again instead there should be a display of message like "you have already added that task" or something like that and that task should not be added 

Current Behavior--
![image](https://github.com/malivinayak/To-Do-Manager/assets/114488917/a95bed68-fbc1-4445-9587-30499d9ba2af)

While it should not allow this thing and display a warning like message

Also the "Tasks" heading should remain hide until there are no tasks added I want to remove these 2 bugs

**Comment by GbCderr14** [comment]
Can you please assign this issue to me

**Comment by malivinayak** [comment]
Thank you for reporting the issue, looking forward for PR

**Comment by GbCderr14** [comment]
Already made the PR can you please review
