### ISSUE TITLE
Feature Request: Add Task Successfully Added Alert

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/To-Do-Manager#35]
A success alert for when a task is successfully added. This alert, styled in a pleasant green color combination, will enhance user experience by providing immediate feedback on successful task addition. This visual cue ensures users are promptly informed about the successful execution of their action, contributing to a more intuitive and user-friendly interface.

Warning Alert demo :
![image](https://github.com/malivinayak/To-Do-Manager/assets/66154908/ae5797ea-29a1-4129-afb7-d1463b402574)

**Comment by malivinayak** [comment]
@Mouli-3542 @GbCderr14 Check out this issue

**Comment by Mouli-3542** [comment]
Alr... i'll work on this

**Comment by kom-senapati** [comment]
The label should be hacktoberfest not hacktoberfest-accepted.

**Comment by malivinayak** [comment]
> The label should be hacktoberfest not hacktoberfest-accepted.

Don't worry about label as it doesn't affect in issue section

**Comment by nikhilgarg26** [comment]
hey @malivinayak the issue has been resolved but i had to combine the `storeTask.js` and `loadTask.js`  to a single file as the window was reloading and the alert was not been shown.
I am pulling a PR do check it out.

**Comment by malivinayak** [comment]
> do check it out.

sure

**Comment by malivinayak** [comment]
> This alert, styled in a pleasant green color combination

https://github.com/malivinayak/To-Do-Manager/pull/39#pullrequestreview-1653458549
@nikhilgarg26
