### ISSUE TITLE
bug: Cant scroll

### ISSUE THREAD

**Issue by kom-senapati** [malivinayak/To-Do-Manager#36]
I added 4 tasks but can't see the last 2 tasks.

**Comment by RaviTejaVattem** [comment]
Hello,

I see that missing `overflow: hidden;` on the parent div is preventing the scroll.

Let me know if I can submit a PR for this.

**Comment by malivinayak** [comment]
> Hello,
> 
> Let me know if I can submit a PR for this.

sure
