### ISSUE TITLE
Adding animations

### ISSUE THREAD

**Issue by Mouli-3542** [malivinayak/To-Do-Manager#37]
**Bubble animation** : A constant random flow of bubbles
Will make a PR if u liked it
![bubblee](https://github.com/malivinayak/To-Do-Manager/assets/143725284/cd51c3db-9cd0-43c9-a3de-2e3b2b265580)

**Comment by malivinayak** [comment]
Closed as not planned

**Comment by Mouli-3542** [comment]
made for fun 😅
