### ISSUE TITLE
Feature Request: Add Task Successfully Delete Alert

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/To-Do-Manager#40]
A success alert for when a task is successfully `deleted`. This alert, styled in a pleasant `red color` combination, will enhance user experience by providing immediate feedback on successful task deletion. This visual cue ensures users are promptly informed about the successful execution of their action, contributing to a more intuitive and user-friendly interface.

Warning Alert demo :
![image](https://github.com/malivinayak/To-Do-Manager/assets/66154908/ae5797ea-29a1-4129-afb7-d1463b402574)

**Comment by nikhilgarg26** [comment]
can i resolve this issue

**Comment by malivinayak** [comment]
> can i resolve this issue

Yes you can

**Comment by malivinayak** [comment]
> can i resolve this issue

@nikhilgarg26 
You can make PR similar to #39 
Don't forget to change the color and add delete icon to alert.

**Comment by nikhilgarg26** [comment]
can provide the code of delete icon ?

**Comment by malivinayak** [comment]
> can you provide the code of delete icon ?
>

You can use any of the following icon:

<table>
<tr></tr>
<tr><td align="center"><b>Code Snippet</b> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </td><td align="center"><b>Icon</b></td></tr>

<tr>
<td>

```html
      <span class='fa fa-times-circle' style='font-size:24px'></span>      
```

</td>
<td>

![image](https://github.com/malivinayak/To-Do-Manager/assets/66154908/5ca4ec96-60f2-411e-892b-89c45757c842)

</td>
</tr>

<tr></tr>

<tr>
<td>

```html
     <span class='fas fa-trash-alt' style='font-size:24px'></span>
```

</td>
<td>

![image](https://github.com/malivinayak/To-Do-Manager/assets/66154908/66a274da-60e5-4591-8883-23c34b7aa6c2)

</td>
</tr>
</table>

Adjust the size via `style='font-size:24px'` and update colors accordingly.

**Comment by GbCderr14** [comment]
@malivinayak  can you please review the PR i have made
