### ISSUE TITLE
Create alert on successful edit the task

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/To-Do-Manager#43]
create alert same as #40 
You can use blue color combination or any other suitable for update option

**Comment by malivinayak** [comment]
@amripandey You can work on this if you like

**Comment by vens8** [comment]
Please assign this to me.

**Comment by malivinayak** [comment]
@amripandey and @vens8 
You both are working on same issue at PR #45 #46

Whoever resolves the requested changes first that PR will be merged
