### ISSUE TITLE
Add a icon and og property

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/To-Do-Manager#44]
- Add of favicon to website.
    ![image](https://github.com/malivinayak/To-Do-Manager/assets/66154908/2524ceb3-3c34-4f8c-90d0-1518f40965eb)

-   Add four basic open graph properties / meta data

**Comment by rahmlad-aramide** [comment]
Hi @malivinayak 
I will like you to assign this issue to me, but before then, I'll like to confirm if you already have the icon you'll like me to use or I should source for it?

**Comment by malivinayak** [comment]
> I'll like to confirm if you already have the icon you'll like me to use or I should source for it?

Thank You for asking but you can use icon of your choice

**Note: ** icon should be uploaded at assets/images folder

**Comment by rahmlad-aramide** [comment]
Alright, no problem. 
And thanks for assigning it to me @malivinayak
